"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-09-10 20:45:05.770429

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outbox_events_idempotency_key"), "outbox_events", ["idempotency_key"], unique=True)
    op.create_index(op.f("ix_outbox_events_scheduled_for"), "outbox_events", ["scheduled_for"], unique=False)
    op.create_index(op.f("ix_outbox_events_status"), "outbox_events", ["status"], unique=False)
    op.create_index("ix_outbox_pending_scheduled", "outbox_events", ["status", "scheduled_for"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("prefix", sa.String(length=10), nullable=False),
        sa.Column("next_task_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("discord_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("lead_discord_id", sa.BigInteger(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "name", name="uq_project_guild_name"),
        sa.UniqueConstraint("guild_id", "prefix", name="uq_project_guild_prefix"),
    )
    op.create_index(op.f("ix_projects_discord_channel_id"), "projects", ["discord_channel_id"], unique=False)
    op.create_index(op.f("ix_projects_guild_id"), "projects", ["guild_id"], unique=False)
    op.create_index(op.f("ix_projects_lead_discord_id"), "projects", ["lead_discord_id"], unique=False)
    op.create_table(
        "squads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("discord_role_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "name", name="uq_squad_guild_name"),
    )
    op.create_index(op.f("ix_squads_discord_role_id"), "squads", ["discord_role_id"], unique=False)
    op.create_index(op.f("ix_squads_guild_id"), "squads", ["guild_id"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("user_discord_id", sa.BigInteger(), nullable=False),
        sa.Column("notify_preference", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("guild_id", "user_discord_id"),
    )
    op.create_table(
        "project_squads",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("squad_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timeline", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["squad_id"], ["squads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "squad_id"),
    )
    op.create_table(
        "squad_members",
        sa.Column("squad_id", sa.UUID(), nullable=False),
        sa.Column("user_discord_id", sa.BigInteger(), nullable=False),
        sa.Column("role_type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["squad_id"], ["squads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("squad_id", "user_discord_id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("task_number", sa.Integer(), nullable=False),
        sa.Column("short_id", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("creator_discord_id", sa.BigInteger(), nullable=False),
        sa.Column("assignee_discord_id", sa.BigInteger(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discord_message_id", sa.BigInteger(), nullable=True),
        sa.Column("discord_thread_id", sa.BigInteger(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "short_id", name="uq_task_guild_short_id"),
    )
    op.create_index(op.f("ix_tasks_assignee_discord_id"), "tasks", ["assignee_discord_id"], unique=False)
    op.create_index(op.f("ix_tasks_due_at"), "tasks", ["due_at"], unique=False)
    op.create_index(op.f("ix_tasks_guild_id"), "tasks", ["guild_id"], unique=False)
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_index(op.f("ix_tasks_short_id"), "tasks", ["short_id"], unique=False)
    op.create_table(
        "task_dependencies",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_task_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["depends_on_task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "depends_on_task_id"),
    )
    op.create_index(
        op.f("ix_task_dependencies_depends_on_task_id"), "task_dependencies", ["depends_on_task_id"], unique=False
    )
    op.create_table(
        "task_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("actor_discord_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("old_status", sa.String(length=30), nullable=True),
        sa.Column("new_status", sa.String(length=30), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_history_task_id"), "task_history", ["task_id"], unique=False)
    op.create_table(
        "task_watchers",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("user_discord_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "user_discord_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_watchers")
    op.drop_index(op.f("ix_task_history_task_id"), table_name="task_history")
    op.drop_table("task_history")
    op.drop_index(op.f("ix_task_dependencies_depends_on_task_id"), table_name="task_dependencies")
    op.drop_table("task_dependencies")
    op.drop_index(op.f("ix_tasks_short_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_guild_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_due_at"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assignee_discord_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("squad_members")
    op.drop_table("project_squads")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_squads_guild_id"), table_name="squads")
    op.drop_index(op.f("ix_squads_discord_role_id"), table_name="squads")
    op.drop_table("squads")
    op.drop_index(op.f("ix_projects_lead_discord_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_guild_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_discord_channel_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index("ix_outbox_pending_scheduled", table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_status"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_scheduled_for"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_idempotency_key"), table_name="outbox_events")
    op.drop_table("outbox_events")
    # ### end Alembic commands ###
